[package]
name = "geopagg"
version = "0.1.0"
edition = "2021"

[dependencies]
adjustp = "0.1.6"
anyhow = "1.0.86"
approx = "0.5.1"
derive-new = "0.6.0"
itertools = "0.13.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
